spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruban?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com #发送邮件服务器
    username: l554725722@163.com #发送邮件的邮箱地址
    password: mbq1314520 #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: l554725722@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
server:
  port: 8000

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.creation.ruban.Entity

kafka:
  servers: 127.0.0.1:9092
  autoCommit: true
  autoCommitInterval: 1000
  sessionTimeOut: 30000
  autoOffsetReset: earliest